### ISSUE TITLE
The future of pantry

### ISSUE THREAD

**Issue by kablamo** [dagolden/pantry#10]
This project seems to be abandoned.  Do you still use it?  I was thinking of using it at $work and submitting some prs.  Is that crazy?

**Comment by xdg** [comment]
I've stopped using Chef and so this project is pretty much dead on my end.  Would you be interested in taking it over?

**Comment by kablamo** [comment]
I've been researching this more and instead of updating Pantry, I've decided to steal your ideas and add them to my tool I've already written to work with Chef.  Sorry for the noise.  Good stuff though -- like all the code you write.
